export const RECEIVED_DREAMS = "RECEIVED_DREAMS";
export const REQUEST_DREAMS = "REQUEST_DREAMS";
export const SELECT_DREAM = "SELECT_DREAM";
export const ADD_NEW_OR_UPDATE_DREAM = "ADD_NEW_OR_UPDATE_DREAM";
export const DELETE_DREAM = "DELETE_DREAM";