let archs = {
  "Cave": "containment, enclosure, Mother Earth, womb, the unconscious, the Underworld",
  "Mountain": "in contrast to the cave, ascent, power, deity, bridge between heaven and earth, navel, center of the world, Ziggurat, Tower of Babel",
  "Hill": "muted form of the mountain",
  "Desert": "both suffering and numinous, God’s presence and his abandonment",
  "Forest": "unconscious projections, unknown and mysterious",
  "Horizon": "the extent and limits of the conscious mind",
  "Lake": "mirror for self-reflection and to see unconscious fantasies in its depth",
  "Land": "territoriality, power, status",
  "Metal": "smelting process is union of male and female",
  "River": "confluence into the sea symbolizes the individual into the absolute, or life (river) to death (sea)",
  "Sea": "undifferentiated primal state, the absolute, origins of life, mother earth",
  "Ocean": "undifferentiated primal state, the absolute, origins of life, mother earth",
  "Stone": "static constancy",
  "Tree": "dynamic regeneration",
  "Mandela": "circle within square or square within circle, sacred meets profane",
  "Quaternity": "all encompassing reality, 4 points of compass, 4 elements of ancient cultures (earth, air, fire & water), 4 rivers in the Garden of Eden, 4 Gospels, 4 seasons, 4 nucleotides, the quaternity further subdivided into 12, the hours of the day, Zodiac signs",
  "Center": "navel, maximum security",
  "Lefthanded": "clumsy, awkward, sinister, underhanded (symbolized by moon, feminine, night, winter, death , illness, evil, hell, representing unconscious)",
  "Righthanded": "competent, effective, powerful, just, fair, (symbolized by sun, masculine, day, summer, life, health, good, heaven, representing conscious)",
  "Earth": "fundamental reality, permanence, fertility, birth, regeneration and finality (entrance to underworld)",
  "Earthquake": "fundamental crisis or change",
  "Air": "fantasy, freedom, infinity, immortality, spirit, and masculine, contrasted to earth which is material and feminine",
  "Fire": "Dual aspect, dangerous power; sex or fury.  Also, light of consciousness, keeps unconscious fears at bay",
  "Water": "primal origin of all things, potentiality, removes contaminants, maintains life.  Also, deluge, destruction and resurrection.  Symbolic of the unconscious (deep water)",
  "Sky": "masculine, identified with deities (contrasted with feminine earth, goddess, fertility).  Represents aspirations, ambition, goals",
  "Sun": "will, royalty, splendor, majesty, warmth, light, healing, goodness, everlasting life  (symbols for the sun include; disc, circle, wheel, eye, swastika, chariot, solar gods, solar animals)",
  "Sunbeams": "light and heat",
  "Underworld": "darkness, evil, sickness and death",
  "Moon": "imagination, cycles of nature, tides, floods, menstruation, passive, reflective, Mother archetype",
  "Mars": "action and destruction",
  "Mercury": "intuition and movement",
  "Jupiter": "judgment and command",
  "Venus": "love and relationship",
  "Saturn": "endurance",
  "Clouds": "promise of rain (fertility)",
  "Comet": "sign of danger, war",
  "Meteorites": "metal from the gods (used to make weapons), sacred stones, linked to male deity, thunder",
  "Rain": "gift from the gods, fertility, divine semen",
  "Rainbow": "bridge or pathway to heaven, mystic serpent, vitality, power",
  "Thunder": "anger of gods, destruction or punishment",
  "lightning": "anger of gods, destruction or punishment",
  "Colors": "active/hot/advancing color red, yellow, orange, white, and retreating/cold/passive colors blue indigo, violet and black.  Green is the transition between advancing and retreating.",
  "Black": "darkness, death, sickness and evil (associated with the Shadow archetype)",
  "White": "light, sun, air, holiness, perfection, innocence, friendship, truce, goodwill",
  "Red": "sun, masculinity, fire, passion, energy, blood, war, rage",
  "Gold": "sun, masculinity, divine power, illumination, consciousness",
  "Brown": "earth, soil, fertility, nature’s womb, autumn melancholy, humility and poverty",
  "Green": "both life and death, unripeness, naivety, hope, immortality",
  "Blue": "infinity, eternal, ultimate",
  "Violet": "religious devotion, grief",
  "Purple": "majesty, royalty",
  "Temple": "square with dome (four corners of earth with domed sky), represents conjunction of heaven and earth, Mandela",
  "Cathedral": "square with dome (four corners of earth with domed sky), represents conjunction of heaven and earth, Mandela",
  "House": "womb, nurturance, Mother archetype, represents the Self archetype",
  "Home": "womb, nurturance, Mother archetype, represents the Self archetype",
  "Kitchen": "nourishment",
  "Bedroom": "sex, birth, death, illness",
  "Bathroom": "purification and regeneration",
  "Drawing Room": "social activity, gossip",
  "Dining Room": "affiliation, hospitality, integration",
  "Basement": "unconscious",
  "Cellar": "unconscious",
  "Foundations": "determines the shape and structure, represents the collective unconscious",
  "Attic": "secrets from the past",
  "Stairs": "themes of descent and ascent (interaction between unconscious and conscious), from Freud it is associated with sexual intercourse",
  "Doors": "open/welcoming, shut/excluding",
  "Façade": "what is shown to the outside world, represents the Personna archetype",
  "Journey": "quest for meaning, ordeal to demonstrate strength or worthiness",
  "Path": "life’s journey, path to individuation",
  "Labyrinth": "life’s journey, path to individuation",
  "Bridge": "overcomes obstacles, associated with rainbow, connection between God and humanity",
  "Egg": "the primal Self, slumbering in the womb/unconscious",
  "Fetus": "the primal Self, slumbering in the womb/unconscious",
  "Serpent": "either gnosis/knowledge and emerging self-awareness, rebirth (shedding skin) or evil",
  "Hero": "part divine, part human, endures an ordeal with evil, dragon, Represents entering adulthood, 2nd birth, severing ties with Mother, proving worth: embracing the Anima",
  "Child": "the undifferentiated self",
  "Gate": "initiation or transition from one state to another",
  "Door": "initiation or transition from one state to another",
  "Garden": "represents the Self archetype",
  "Key": "open or closing, initiation, transition",
  "Ladder": "social or religious hierarchy, realization of potential, elevation of spirit, reaching to heaven",
  "Lamp": "consciousness",
  "Lotus": "spiritual aspirations, death and rebirth, purity",
  "Mirror": "self-realization",
  "Feathers": "air and flight, ability to connect with the spirits or the dead",
  "Trickster": "represents the Shadow archetype",
  "Axe": "justice, punishment, law",
  "Chisel": "active male principle",
  "Compass": "the Self archetype",
  "Knife": "active male principle, also represents analytic conscious mind",
  "Mortar and pestle": "sexual intercourse",
  "Plough": "fertilizing the feminine",
  "Harp": "angels, heaven, wind deities",
  "Drum": "war",
  "Bicycle": "independence and autonomy",
  "Wheel": "the individuating self",
  "Boat": "symbolic of the body, carrying the self through life",
  "Anchor": "one’s sense of security",
  "Hull": "womb, nourishment, safety, related to the Ark",
  "Sails": "fertility, life",
  "Car": "self-concept",
  "Motorcycle": "masculine power and risk-taking",
  "Spacecraft": "spherical discs, projections of the self to the heavens",
  "Train": "life’s journey in a social context",
  "Engine": "libido, energy, motivation",
  "Mother": "child-rearing, nurturance, home-making",
  "Father": "law and order, authority",
  "Son": "self-centered, unconcerned with collective social responsibilities",
// "Hero": "overcomes self-centeredness, oriented to collective needs",
  "Wise Man": "ideas, meaning",
  "Necktie": "phallic symbol (also plough, hammer, rifle, revolver, sabres, sword)",
  "Cord" : "individual life",
  "Rope": "individual life",
  "Knot": "bonding, unity",
  "Ring": "completion, wholeness, continuity, union of opposites",
  "Hunter": "power figure of the Shadow",
  "Maypole": "phallic symbol with feminine discus on the top, fertility",
  "Chair": "symbol of authority or rank",
  "Crown": "circle representing wholeness, unity, perfection, supreme power",
  "Sceptre": "extension of the arm, phallic symbol, sovereignty",
  "Fish": "symbolic of the collective unconscious",
  "Amphibian": "transformation, purification",
  "Frog": "transition between conscious and unconscious",
  "Reptiles": "cruelty, aggression",
  "Fox": "theft, craftiness, trickster",
  "Bear": "mother archetype with cubs, or aggression and brutality",
  "Lion": "rising sun (young lion) and setting sun (old lion), lioness nurturing mother",
  "Spider": "the web is a Mandela, unity of opposites: creating and killing",
  "Stag": "drops rack and regenerates: tree of life, regeneration, growth, fertility",
  "Wolf": "nurturing or destructive",
  "Bull": "fertility, virility",
  "Camel": "Endurance and sobriety",
  "Cat": "good omen or evil omen, depending on color",
  "Cow": "represents the mother archetype",
  "Dog": "loyal guardian, affection and faithfulness",
  "Horse": "the conveyance of the gods and heroes",
  "Lamb": "spring, innocence, purity, new life",
  "Dove": "immortal soul",
  "Ducks": "marriage",
  "Eagle": "spiritual aspiration",
  "Falcon": "associated with sun, male, light",
  "Heron": "serpent-killer, battle of good and evil",
  "Owl": "lunar, reflective, introverted, wise",
  "Peacock": "vanity or symbol of the sun disk",
  "Bee": "self-discipline and organization",
  "Butterfly": "transformation and rebirth",
  "Bat": "death and immortality",
  "Acorn": "individuation of the self",
  "Willow": "grief, lost love, death",
  "Headgear": "footwear and jewelry: social status",
  "Uniform": "identification with social group",
  "Ankle": "the aspiration to higher consciousness",
  "Arm": "power, aggression",
  "Back": "the unconscious, hidden self",
  "Beard": "wisdom, maturity",
  "Breast": "maternity, nurturance and plenty",
  "Eye": "consciousness, intelligence, insight",
  "Foot": "phallic symbol",
  "Fat": "in societies with scarcity of food, high social status, in societies with plenty of food, low social status",
  "Fist": "anger",
  "Heart": "center of self"
}
const keys = Object.keys(archs);

for (let i = 0; i < keys.length; i++) {
  keys[i] = keys[i].toLowerCase();
}

export const keyWords = keys;

export const commonWords = ['i','a','about','an','and','are','as','at','be','by','com','de','en','for','from','how','in','is','it','la','of','on','or','that','the','this','to','was','what','when','where','who','will','with','und','the','www'];
